### ISSUE TITLE
setup continuous integration using travis

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit-app-ios#22]

**Comment by AntonioLangiu** [comment]
I think this is not an issue of this repository. We have to change files in the measurement-kit repo. 

I made a [new branch](https://github.com/measurement-kit/measurement-kit/tree/fix/build-ios) in measurement-kit to fix this issue.

**Comment by AntonioLangiu** [comment]
Now it works, but travis print this text:
```
WARNING: Using Objective-C testing without specifying a scheme 
and either a workspace or a project is deprecated.
Check out our documentation for more information: 
http://about.travis-ci.org/docs/user/languages/objective-c/
```

I think that to remove this warning we should try to compile also the project with Xcode and not just the library with `pod install`. @bassosimone

**Comment by AntonioLangiu** [comment]
A solution to compile the library from the measurement-kit repo is to use `branch` inside the travis.yml file, like they do in [this](https://github.com/urho3d/Urho3D/blob/master/.travis.yml) cross-platform project. 

I will try it in a new branch to see if it works.

**Comment by bassosimone** [comment]
I do not fully understand you last comment.

**Comment by bassosimone** [comment]
Ok, now that I fully understand your comment (github branches are a thing, travis-ci branches are another thing and live inside the travis configuration file), I'd say let's go down that route and try to have the same travis configuration file coordinate automatic build both for ios and linux. (Side question: is it possible with travis to also compile for MacOS?)
