### ISSUE TITLE
Add target to the podfile 

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit-app-ios#23]
We could use a "target" in the podfile to speed up the compilation on travis (building just one architecture instead of 5).

[This](https://github.com/CocoaPods/CocoaPods/issues/1499#issuecomment-26778666) can be a solution.

**Comment by bassosimone** [comment]
I'd say that we compile everything every time, so we are sure that everything is in order. At least now that we are at the beginning. We may want to change this policy later in the future.
