### ISSUE TITLE
Update the App and check it with cocoapod

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/measurement-kit-app-ios#25]
We pushed the first pod to coocapod with all the new features of measurement-kit. We need now to update the App using the new Api.

**Comment by lorenzoPrimi** [comment]
@AntonioLangiu has this been done? otherwise let me understand what I should do.

**Comment by AntonioLangiu** [comment]
I think this has be done @lorenzoPrimi. We are using the last available API :+1:
