### ISSUE TITLE
Fix crash when running DNS injection

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit-app-ios#4]
When running the DNS injection test of first boot the app crashes.

**Comment by bassosimone** [comment]
I don't fully understand what you mean with "of first boot". Do you mean that this happens the first time you run the app after you've started up the iDevice?

**Comment by lorenzoPrimi** [comment]
When you run the DNS injection as first test after starting the app.

**Comment by bassosimone** [comment]
Understood, thanks. Is there a stacktrace describing the error?

**Comment by lorenzoPrimi** [comment]
@bassosimone @hellais try to debug the app from Xcode, it seems to be a problem of the library.

**Comment by bassosimone** [comment]
Issue addressed by #14.
